version: '2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: local/phoenix
    volumes:
      - .:/srv/www/app
    ports:
      - "4000:4000"
    links:
      - db
    depends_on:
      - db

  db:
    image: postgres:9.4
    ports:
      - "5432"


